/run/printProgress 100000
/gun/particle gamma
/analysis/setFileName /scratch/jmayer/G4/10
/gun/energy 10 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/20
/gun/energy 20 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/30
/gun/energy 30 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/40
/gun/energy 40 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/50
/gun/energy 50 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/60
/gun/energy 60 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/70
/gun/energy 70 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/80
/gun/energy 80 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/90
/gun/energy 90 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/100
/gun/energy 100 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/110
/gun/energy 110 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/120
/gun/energy 120 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/130
/gun/energy 130 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/140
/gun/energy 140 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/150
/gun/energy 150 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/160
/gun/energy 160 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/170
/gun/energy 170 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/180
/gun/energy 180 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/190
/gun/energy 190 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/200
/gun/energy 200 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/210
/gun/energy 210 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/220
/gun/energy 220 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/230
/gun/energy 230 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/240
/gun/energy 240 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/250
/gun/energy 250 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/260
/gun/energy 260 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/270
/gun/energy 270 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/280
/gun/energy 280 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/290
/gun/energy 290 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/300
/gun/energy 300 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/310
/gun/energy 310 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/320
/gun/energy 320 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/330
/gun/energy 330 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/340
/gun/energy 340 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/350
/gun/energy 350 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/360
/gun/energy 360 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/370
/gun/energy 370 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/380
/gun/energy 380 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/390
/gun/energy 390 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/400
/gun/energy 400 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/410
/gun/energy 410 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/420
/gun/energy 420 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/430
/gun/energy 430 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/440
/gun/energy 440 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/450
/gun/energy 450 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/460
/gun/energy 460 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/470
/gun/energy 470 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/480
/gun/energy 480 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/490
/gun/energy 490 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/500
/gun/energy 500 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/510
/gun/energy 510 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/520
/gun/energy 520 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/530
/gun/energy 530 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/540
/gun/energy 540 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/550
/gun/energy 550 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/560
/gun/energy 560 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/570
/gun/energy 570 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/580
/gun/energy 580 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/590
/gun/energy 590 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/600
/gun/energy 600 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/610
/gun/energy 610 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/620
/gun/energy 620 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/630
/gun/energy 630 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/640
/gun/energy 640 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/650
/gun/energy 650 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/660
/gun/energy 660 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/670
/gun/energy 670 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/680
/gun/energy 680 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/690
/gun/energy 690 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/700
/gun/energy 700 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/710
/gun/energy 710 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/720
/gun/energy 720 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/730
/gun/energy 730 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/740
/gun/energy 740 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/750
/gun/energy 750 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/760
/gun/energy 760 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/770
/gun/energy 770 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/780
/gun/energy 780 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/790
/gun/energy 790 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/800
/gun/energy 800 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/810
/gun/energy 810 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/820
/gun/energy 820 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/830
/gun/energy 830 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/840
/gun/energy 840 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/850
/gun/energy 850 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/860
/gun/energy 860 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/870
/gun/energy 870 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/880
/gun/energy 880 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/890
/gun/energy 890 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/900
/gun/energy 900 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/910
/gun/energy 910 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/920
/gun/energy 920 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/930
/gun/energy 930 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/940
/gun/energy 940 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/950
/gun/energy 950 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/960
/gun/energy 960 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/970
/gun/energy 970 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/980
/gun/energy 980 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/990
/gun/energy 990 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1000
/gun/energy 1000 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1010
/gun/energy 1010 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1020
/gun/energy 1020 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1030
/gun/energy 1030 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1040
/gun/energy 1040 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1050
/gun/energy 1050 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1060
/gun/energy 1060 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1070
/gun/energy 1070 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1080
/gun/energy 1080 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1090
/gun/energy 1090 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1100
/gun/energy 1100 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1110
/gun/energy 1110 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1120
/gun/energy 1120 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1130
/gun/energy 1130 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1140
/gun/energy 1140 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1150
/gun/energy 1150 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1160
/gun/energy 1160 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1170
/gun/energy 1170 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1180
/gun/energy 1180 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1190
/gun/energy 1190 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1200
/gun/energy 1200 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1210
/gun/energy 1210 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1220
/gun/energy 1220 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1230
/gun/energy 1230 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1240
/gun/energy 1240 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1250
/gun/energy 1250 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1260
/gun/energy 1260 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1270
/gun/energy 1270 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1280
/gun/energy 1280 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1290
/gun/energy 1290 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1300
/gun/energy 1300 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1310
/gun/energy 1310 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1320
/gun/energy 1320 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1330
/gun/energy 1330 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1340
/gun/energy 1340 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1350
/gun/energy 1350 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1360
/gun/energy 1360 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1370
/gun/energy 1370 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1380
/gun/energy 1380 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1390
/gun/energy 1390 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1400
/gun/energy 1400 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1410
/gun/energy 1410 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1420
/gun/energy 1420 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1430
/gun/energy 1430 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1440
/gun/energy 1440 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1450
/gun/energy 1450 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1460
/gun/energy 1460 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1470
/gun/energy 1470 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1480
/gun/energy 1480 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1490
/gun/energy 1490 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1500
/gun/energy 1500 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1510
/gun/energy 1510 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1520
/gun/energy 1520 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1530
/gun/energy 1530 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1540
/gun/energy 1540 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1550
/gun/energy 1550 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1560
/gun/energy 1560 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1570
/gun/energy 1570 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1580
/gun/energy 1580 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1590
/gun/energy 1590 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1600
/gun/energy 1600 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1610
/gun/energy 1610 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1620
/gun/energy 1620 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1630
/gun/energy 1630 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1640
/gun/energy 1640 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1650
/gun/energy 1650 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1660
/gun/energy 1660 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1670
/gun/energy 1670 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1680
/gun/energy 1680 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1690
/gun/energy 1690 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1700
/gun/energy 1700 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1710
/gun/energy 1710 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1720
/gun/energy 1720 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1730
/gun/energy 1730 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1740
/gun/energy 1740 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1750
/gun/energy 1750 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1760
/gun/energy 1760 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1770
/gun/energy 1770 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1780
/gun/energy 1780 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1790
/gun/energy 1790 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1800
/gun/energy 1800 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1810
/gun/energy 1810 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1820
/gun/energy 1820 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1830
/gun/energy 1830 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1840
/gun/energy 1840 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1850
/gun/energy 1850 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1860
/gun/energy 1860 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1870
/gun/energy 1870 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1880
/gun/energy 1880 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1890
/gun/energy 1890 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1900
/gun/energy 1900 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1910
/gun/energy 1910 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1920
/gun/energy 1920 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1930
/gun/energy 1930 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1940
/gun/energy 1940 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1950
/gun/energy 1950 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1960
/gun/energy 1960 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1970
/gun/energy 1970 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1980
/gun/energy 1980 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/1990
/gun/energy 1990 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2000
/gun/energy 2000 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2010
/gun/energy 2010 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2020
/gun/energy 2020 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2030
/gun/energy 2030 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2040
/gun/energy 2040 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2050
/gun/energy 2050 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2060
/gun/energy 2060 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2070
/gun/energy 2070 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2080
/gun/energy 2080 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2090
/gun/energy 2090 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2100
/gun/energy 2100 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2110
/gun/energy 2110 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2120
/gun/energy 2120 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2130
/gun/energy 2130 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2140
/gun/energy 2140 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2150
/gun/energy 2150 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2160
/gun/energy 2160 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2170
/gun/energy 2170 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2180
/gun/energy 2180 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2190
/gun/energy 2190 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2200
/gun/energy 2200 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2210
/gun/energy 2210 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2220
/gun/energy 2220 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2230
/gun/energy 2230 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2240
/gun/energy 2240 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2250
/gun/energy 2250 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2260
/gun/energy 2260 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2270
/gun/energy 2270 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2280
/gun/energy 2280 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2290
/gun/energy 2290 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2300
/gun/energy 2300 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2310
/gun/energy 2310 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2320
/gun/energy 2320 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2330
/gun/energy 2330 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2340
/gun/energy 2340 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2350
/gun/energy 2350 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2360
/gun/energy 2360 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2370
/gun/energy 2370 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2380
/gun/energy 2380 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2390
/gun/energy 2390 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2400
/gun/energy 2400 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2410
/gun/energy 2410 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2420
/gun/energy 2420 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2430
/gun/energy 2430 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2440
/gun/energy 2440 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2450
/gun/energy 2450 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2460
/gun/energy 2460 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2470
/gun/energy 2470 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2480
/gun/energy 2480 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2490
/gun/energy 2490 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2500
/gun/energy 2500 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2510
/gun/energy 2510 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2520
/gun/energy 2520 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2530
/gun/energy 2530 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2540
/gun/energy 2540 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2550
/gun/energy 2550 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2560
/gun/energy 2560 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2570
/gun/energy 2570 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2580
/gun/energy 2580 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2590
/gun/energy 2590 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2600
/gun/energy 2600 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2610
/gun/energy 2610 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2620
/gun/energy 2620 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2630
/gun/energy 2630 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2640
/gun/energy 2640 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2650
/gun/energy 2650 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2660
/gun/energy 2660 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2670
/gun/energy 2670 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2680
/gun/energy 2680 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2690
/gun/energy 2690 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2700
/gun/energy 2700 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2710
/gun/energy 2710 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2720
/gun/energy 2720 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2730
/gun/energy 2730 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2740
/gun/energy 2740 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2750
/gun/energy 2750 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2760
/gun/energy 2760 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2770
/gun/energy 2770 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2780
/gun/energy 2780 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2790
/gun/energy 2790 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2800
/gun/energy 2800 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2810
/gun/energy 2810 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2820
/gun/energy 2820 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2830
/gun/energy 2830 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2840
/gun/energy 2840 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2850
/gun/energy 2850 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2860
/gun/energy 2860 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2870
/gun/energy 2870 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2880
/gun/energy 2880 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2890
/gun/energy 2890 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2900
/gun/energy 2900 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2910
/gun/energy 2910 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2920
/gun/energy 2920 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2930
/gun/energy 2930 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2940
/gun/energy 2940 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2950
/gun/energy 2950 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2960
/gun/energy 2960 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2970
/gun/energy 2970 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2980
/gun/energy 2980 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/2990
/gun/energy 2990 keV
/run/beamOn 10000000
/analysis/setFileName /scratch/jmayer/G4/3000
/gun/energy 3000 keV
/run/beamOn 10000000
